name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install --repo-update
        working-directory: ios

      - name: Build iOS release
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qr FlutterIpaExport.ipa Payload

      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
